### ISSUE TITLE
small bug in small sample adjustments

### ISSUE THREAD

**Issue by s3alfisc** [droodman/WildBootTests.jl#11]
Hi David, there is a small bug in the small sample adjustments (version 0.7.9): 

```
using WildBootTests, CSV, DataFrames, StatsModels
d = download("https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/sandwich/PetersenCL.csv");
df = CSV.read(d, DataFrame);
f = @formula(y ~ 1 + x);                             # state OLS model
f = apply_schema(f, schema(f, df));                  # link model to data
resp, predexog = modelcols(f, df);                   # extract response & (exogenous) predictor variables
clustid = df.firm;                                   # extract clustering variable
R = [0 1]; r = [1];                                  # put null in Rβ = r form, where β is parameter vector

test1 = wildboottest(R, r; resp, predexog, clustid, small = false, clusteradj = true, clustermin = false)
# z  = 0.689
# p  = 0.456
# CI = [0.9346845397071931 1.1337785409767502]
```
but 

```
test2 = wildboottest(R, r; resp, predexog, clustid, small = false, clusteradj = true, clustermin = true)
# z  =   NaN
# p  = 0.456
```
So `z = NaN` and no confidence interval is reported / computed. As the p-value is calculated and stable across the two ssc corrections, I would guess that you apply the corrections 'after' the bootstrap? 

Beyond that, there is currently no documentation of the `clusteradj` and `clustermin` function arguments available. Here is a potential first draft from my side:

* `small::Bool=true`: if true, a small-sample corrections of the form (N-k) / (N-1) * ((G-1) / G) is applied, where N is the number of observations, k the number of estimated coefficients, and G the number of clusters. For further control over small sample correction, use the fedfadj, clusteradj and clustermin function arguments 
* `fedfadj::Integer=nfe`: degrees of freedom that fixed effects (if any) should be taken to consume
* `clusteradj::Bool = true`: True if the small sample adjustment factor for clusters (G-1)/G is supposed to be switched on, false otherwise
* `clustermin::Bool = false`: For multiway clustering, should G_i be set as the number of unique clusters per clustering dimension, or should G_i be set as the minimum number of clusters across clustering dimensions for all dimensions? false by default

**Comment by droodman** [comment]
Thanks for the bug report and documentation prod. I think version 0.7.10, now posted addresses these, and also fixes some other obscure bugs.
