### ISSUE TITLE
Add StableRNGs as dependency?

### ISSUE THREAD

**Issue by s3alfisc** [droodman/WildBootTests.jl#12]
Hi David, would you mind adding the `StableRNGs` package as a dependency? I think you dropped it at some point. I have recently switched to using `StableRNGs` in `fwildclusterboot` to control seeding in Julia, and now a range of tests fail on [github actions](https://github.com/s3alfisc/fwildclusterboot/runs/5890709292?check_suite_focus=true) as `StableRNGs` is not installed / imported with `WildBootTests.jl`. If you have good reasons against having it as a dependency, I can also be explicit in fwildclusterboot's description file and add it as a dependency there, but this will (slightly) increase the amount of work potential users have to go through before running `WildBootTests.jl` through `fwildclusterboot`.

**Comment by droodman** [comment]
Posting now as version 0.7.13.

**Comment by s3alfisc** [comment]
Thanks!
