### ISSUE TITLE
Error in bootstrap with fixed effects?

### ISSUE THREAD

**Issue by s3alfisc** [droodman/WildBootTests.jl#17]
Hi David, 

I finally came around to look at [this issue](https://github.com/s3alfisc/fwildclusterboot/issues/105), which arrived with `WildBootTests.jl` 0.9.7 (I believe). In essence, results from the julia algo no longer match the R algo's when a fixed effect is projected out in the bootstrap. 

In the current version of WildBootTests, it looks like results differ when demeaning within the bootstrap vs not. Note that I drop all small sample adjustments that involve the number of regressors, k.

Here is a short code example: 

```julia
using WildBootTests, CSV, DataFrames, StatsModels, Plots, StableRNGs
d = download("https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/sandwich/PetersenCL.csv");
df = CSV.read(d, DataFrame);
N = size(df, 1)  # Number of columns in df
fe = rand([0, 1], N)
df.fe = fe
clustid = df.firm;  
```
The model without fixed effect demeaning in the bootstrap: 

```julia
# model 1
f = @formula(y ~ 1 + x + fe);                            
f = apply_schema(f, schema(f, df));                
resp, predexog = modelcols(f, df);                 
R = [0 1 0 ]; r = [1];                                 
test = wildboottest(R, r; resp, predexog, clustid, rng = StableRNG(123), fedfadj = 0, small = false)  
#z  = 0.6914
#p  = 0.4935
#CI = [0.9371 1.132]
```

A model with fixed effect demeaning in the bootstrap: 

```julia
# model 2
f = @formula(y ~ 1 + x + fe );                            
f = apply_schema(f, schema(f, df));                
resp, predexog = modelcols(f, df);                 
R = [0 1 0]; r = [1];                                 
test = wildboottest(R, r; resp, predexog, clustid, feid = fe, rng = StableRNG(123), fedfadj = 0, small = false)  
#z  = 0.6914
#p  = 0.4925
#CI = [0.9375 1.132]
```

And an alternative specification:

```julia
# model 3
f = @formula(y ~ 1 + x);                            
f = apply_schema(f, schema(f, df));                
resp, predexog = modelcols(f, df);                 
R = [0 1]; r = [1];                                 
test = wildboottest(R, r; resp, predexog, clustid, feid = fe, rng = StableRNG(123), fedfadj = 0, small = false)  
#z  = 0.6914
#p  = 0.4925
#CI = [0.9375 1.132]
```
Note that the z statistics match, but the p-values and CIs differ when using the feid argument vs not. 

Btw, are both specifications of model 2 and model 3 allowed? `fwildclusterboot` currently uses specification 3, i.e. `predexog` does not contain the feid variable. Should model 2 not throw an error? 

Best, Alex

**Comment by s3alfisc** [comment]
I have just finished running my tests against `WildBootTests` version `0.9.0`, and the tests pass without a problem. I have also replicated the examples above, which produce matching outcomes for pvalues, tstats and CIs under 0.9.0.

**Comment by droodman** [comment]
Thank you, Alex. I think I've fixed this in version 0.9.8, which has just [posted to the general registry](https://github.com/JuliaRegistries/General/actions/runs/5322456455/jobs/9638928760?pr=85919).

**Comment by droodman** [comment]
As for the question about specifications. If the user wants to through the FE indicator into the data matrix, wildboottests() will accept that. It will of course be completely removed when the FE are partialled out. But I don't think there's any need to throw an error.

**Comment by s3alfisc** [comment]
All test pass with version `0.9.8`. 👍 Regarding the specification - makes good sense to me, just wanted to make sure that both specifications are indeed equivalent =)
