### ISSUE TITLE
Documentation is not deployed?

### ISSUE THREAD

**Issue by asinghvi17** [droodman/WildBootTests.jl#18]
Hey, I clicked on the documentation link in the README but got a 404.  It seems like you don't have a `gh-pages` branch, which Documenter expects to deploy to.  You would also have to point Pages to that branch in the repo settings to get a deployment.

Best,
Anshul.

**Comment by asinghvi17** [comment]
I would also recommend that you add `docs/build` to your `.gitignore`...

**Comment by droodman** [comment]
Thank you for the nudge @asinghvi17. I had been mystified for a long time by a bug in my documentation set up. I think it is working now.
