### ISSUE TITLE
Announce on Julia Discourse

### ISSUE THREAD

**Issue by azev77** [droodman/WildBootTests.jl#6]
Hi and thank you for this package!
Have you considered announcing it on Julia Discourse?
https://discourse.julialang.org/
It can give the package useful publicity

**Comment by droodman** [comment]
Thanks! I think I'm just about ready. I've struggled to get the "time-to-first-inference" down to a reasonable amount, and just now got it to 12 seconds, which I think is almost tolerable.

**Comment by droodman** [comment]
Done! https://discourse.julialang.org/t/new-wildboottests-for-wild-bootstrap-based-inference-on-linear-models/73567
