### ISSUE TITLE
Time-to-first-boottest significantly increased (with v.0.7.4?)

### ISSUE THREAD

**Issue by s3alfisc** [droodman/WildBootTests.jl#9]
Hi David, I just updated to v.0.7.4, and the 'time-to-first-boottest' seems to have significantly increased - at least on my PC, the first call of `wildboottest()` takes now around 60-90 seconds. I am not sure if this was introduced in 0.7.4 or potentially earlier (I think to recall 0.7.2 was pretty fast). 

```
using WildBootTests, CSV, DataFrames, StatsModels
d = download("https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/sandwich/PetersenCL.csv");
df = CSV.read(d, DataFrame);
f = @formula(y ~ 1 + x);                             # state OLS model
f = apply_schema(f, schema(f, df));                  # link model to data
resp, predexog = modelcols(f, df);                   # extract response & (exogenous) predictor variables
clustid = df.firm;                                   # extract clustering variable
R = [0 1]; r = [1];                                  # put null in Rβ = r form, where β is parameter vector

@time test = wildboottest(R, r; resp, predexog, clustid);  # run test
# 87.616350 seconds (117.95 M allocations: 5.939 GiB, 3.94% gc time, 99.95% compilation time)
```
For v0.7.3: 
```
julia> @time test = wildboottest(R, r; resp, predexog, clustid)
144.669844 seconds (117.02 M allocations: 5.897 GiB, 3.27% gc time, 99.96% compilation time)
```
For v0.7.2, latency was also around 2 minutes. So it looks like this might just be on  my pc & the latency issues I experience were not introduced by v.0.7.4. So I will close this issue.

**Comment by droodman** [comment]
No, I think you were right there was a probl

**Comment by droodman** [comment]
No, I think you were right there was a problem. Try version 0.7.5, just posted.
In this version I have also dropped the turbo option; I don't know if you were using it, but it was a source of a lot of these delays. And I have changed the default to Float64.

**Comment by droodman** [comment]
Ach, I think there is still a problem. This is a frustrating aspect of Julia.

**Comment by s3alfisc** [comment]
0.7.5 is doing much better - around 30 seconds on my windows machine.

**Comment by s3alfisc** [comment]
But running `wildboottest()` trough `fwildclusterboot` now produces this error: 

```ERROR: LoadError: MethodError: no method matching namemap(::Type{AuxWtType})
The applicable method may be too new: running in world age 31639, while current world is 31672.
Closest candidates are:
  namemap(::Type{AuxWtType}) at C:\...\Programs\Julia-1.7.2\share\julia\base\Enums.jl:201 (method too new to be called from this world context.)
```
Maybe this is the issue you mention above? - I will spend some time debugging what's going on.

**Comment by droodman** [comment]
I forgot to mention that I bumped the Julia version requirement up to 1.7.0. Does that help explain it?

**Comment by droodman** [comment]
Googling around a bit, it looks like this issue could be insidious. Is it recurring? Since it seems to be associated with the use of enumerated data types such as `@enum PType symmetric equaltail lower upper`, I could try dropping those. I've been thinking that it would be more "Julian" to use symbols anyway, while still allowing strings as an alternative. Then one could do `wildboottests(..., ptype = :symmetric)` or `wildboottests(..., ptype = "symmetric")`.

**Comment by s3alfisc** [comment]
Hi David - I have no idea what has been going on - but I have just re-installed my entire Julia setup and now everything works smoothly: the error above has vanished. I have been running Julia 1.7.0 for a while now, so I don't think that's the source of the error. In consequence, I don't think there is any urgency in replacing the enumerated data types, and as long as you keep the option to use strings, I'll be happy :)
